{{- if .Values.alertmanager.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: alertmanager
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "alertmanager.fullname" . }}
data:
{{ toYaml .Values.alertmanagerFiles | indent 2 }}
{{- end }}
