{{- if and .Values.alertmanager.enabled .Values.alertmanager.ingress.enabled -}}
{{- $serviceName := include "alertmanager.fullname" . }}
{{- $servicePort := .Values.alertmanager.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
{{ toYaml .Values.alertmanager.ingress.annotations | indent 4}}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: alertmanager
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "alertmanager.fullname" . }}
spec:
  {{- if .Values.alertmanager.ingress.tls.enabled }}
  tls:
    - hosts:
      {{- range .Values.alertmanager.ingress.hosts }}
      - {{ . }}
      {{- end }}
      secretName: {{ .Values.alertmanager.ingress.tls.secretName }}
  {{- end }}
  rules:
    {{- range .Values.alertmanager.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end -}}
{{- end -}}
