apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "namenode-fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "namenode-fullname" . }}
spec:
  serviceName: {{ template "namenode-fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        release: "{{ .Release.Name }}"
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: {{ template "namenode-fullname" . }}
    spec:
      containers:
        - name: hdfs-namenode
          image: "{{ .Values.namenode.image.repository }}{{ .Values.namenode.image.name }}:{{ .Values.namenode.image.tag }}"
          imagePullPolicy: "{{ .Values.namenode.image.pullPolicy }}"
          env:
            - name: CLUSTER_NAME
              value: hdfs-k8s
            - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
              value: "false"
            - name: HDFS_CONF_dfs_client_use_datanode_hostname
              value: "false"
            - name: HDFS_CONF_dfs_datanode_use_datanode_hostname
              value: "false"
          resources:
{{ toYaml .Values.datanode.resources | indent 12 }}
          ports:
          - containerPort: {{ .Values.namenode.port }}
            name: fs
          volumeMounts:
            - name: hdfs-configs
              mountPath: /etc/hadoop/hdfs-site.xml
              subPath: hdfs-site.xml
            - name: datadir
              mountPath: /hadoop/dfs/data
      volumes:
        - configMap:
            name: {{ template "configmap-fullname" . }}
            items:
            - key: hdfs-site.xml
              path: hdfs-site.xml
          name: hdfs-configs
        {{- if eq .Values.namenode.persistence.type "emptyDir" }}
        - name: datadir
          emptyDir: {}
        {{- else if eq .Values.namenode.persistence.type "hostPath" }}
        - name: datadir
          hostPath:
	          path: "{{ .Values.namenode.persistence.hostPath }}"
        {{- end }}
  {{- if eq .Values.namenode.persistence.type "PersistentVolumeClaim" }}
  volumeClaimTemplates:
  - metadata:
      name: datadir
      {{- if .Values.namenode.persistence.storageClass }}
      annotations:
        volume.beta.kubernetes.io/storage-class: "{{ .Values.namenode.persistence.storageClass }}"
      {{- end }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.namenode.persistence.volumeSize }}
  {{- end }}
