{{- if .Values.configFiles }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "kafka-fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "kafka-fullname" . }}
data:
{{ toYaml .Values.configFiles | indent 2 }}
{{- end }}