apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka-fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "kafka-fullname" . }}
spec:
  ports:
  - port: {{ .Values.port }}
    name: port
  clusterIP: None
  selector:
    app: {{ template "kafka-fullname" . }}
