apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "leonardocms-fullname" . }}
  labels:
    app: {{ template "leonardocms-fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
