datanode:
  replicas: 3
  image:
    repository: mirantisworkloads/
    name: hadoop-datanode
    tag: 2.8.1
    pullPolicy: IfNotPresent

  antiAffinity: "soft" # or "hard"

  persistence:
    type: emptyDir # or hostPath or PersistentVolumeClaim

    #storageClass: ""
    volumeSize: 10Gi

    hostPath: ""

  resources:
    #requests:
    #  cpu: 1
    #  memory: 1Gi
    #limits:
      #cpu: 4
      #memory: 4Gi

namenode:
  port: 8020
  image:
    repository: mirantisworkloads/
    name: hadoop-namenode
    tag: 2.8.1
    pullPolicy: IfNotPresent

  persistence:
    type: emptyDir # or hostPath or PersistentVolumeClaim

    #storageClass: ""
    volumeSize: 10Gi

    hostPath: ""

  resources:
    #requests:
    #  cpu: 1
    #  memory: 1Gi
    #limits:
    #  cpu: 4
    #  memory: 4Gi

  ui:
    port: 50070
    service:
      type: NodePort # or ClusterIP or LoadBalancer

      nodePort: ""

      loadBalancerIP: ""
      loadBalancerSourceRanges: []

      annotations: {}

    ingress:
      enabled: false
      hosts: []
        #   - some.domain
      tls:
        enabled: false
        secretName: ""
      annotations: {}
        #   kubernetes.io/ingress.class: nginx
