dependencies:
- name: zookeeper
  version: ^1.x
  repository: https://mirantisworkloads.storage.googleapis.com/
  condition: zookeeper.deployChart
- name: kafka
  version: ^1.x
  repository: https://mirantisworkloads.storage.googleapis.com/
  condition: kafka.deployChart
- name: spark
  version: ^3.x
  repository: https://mirantisworkloads.storage.googleapis.com/
  condition: spark.deployChart
- name: hdfs
  version: ^2.x
  repository: https://mirantisworkloads.storage.googleapis.com/
  condition: hdfs.deployChart
- name: cassandra
  version: ^1.x
  repository: https://mirantisworkloads.storage.googleapis.com/
  condition: cassandra.deployChart
