dependencies:
- name: zookeeper
  version: ^1.x
  repository: https://mirantisworkloads.storage.googleapis.com/
  condition: zookeeper.deployChart
- name: cassandra
  version: ^1.x
  repository: https://mirantisworkloads.storage.googleapis.com/
  condition: cassandra.enabled,cassandra.deployChart
