apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: server
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "server.fullname" . }}
data:
{{ toYaml .Values.serverFiles | indent 2 }}
