apiVersion: v1
kind: Service
metadata:
  name: {{ template "zk-fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "zk-fullname" . }}
spec:
  ports:
  - port: {{ .Values.serverPort }}
    name: server
  - port: {{ .Values.leaderElectionPort }}
    name: leader-election
  - port: {{ .Values.clientPort }}
    name: client
  clusterIP: None
  selector:
    app: {{ template "zk-fullname" . }}
