{{- if .Values.kubeStateMetrics.enabled -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: kube-state-metrics
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "kubeStateMetrics.fullname" . }}
spec:
  replicas: {{ .Values.kubeStateMetrics.replicas }}
  template:
    metadata:
    {{- if .Values.kubeStateMetrics.podAnnotations }}
      annotations:
{{ toYaml .Values.kubeStateMetrics.podAnnotations | indent 8 }}
    {{- end }}
      labels:
        app: {{ template "name" . }}
        component: kube-state-metrics
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: kube-state-metrics
          image: "{{ .Values.kubeStateMetrics.image.repository }}{{ .Values.kubeStateMetrics.image.name }}:{{ .Values.kubeStateMetrics.image.tag }}"
          imagePullPolicy: "{{ .Values.kubeStateMetrics.image.pullPolicy }}"
          ports:
            - containerPort: 8080
          resources:
{{ toYaml .Values.kubeStateMetrics.resources | indent 12 }}
{{- end }}
