{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "master-fullname" . }}
  labels:
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "master-fullname" . }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
      {{- range .Values.ingress.hosts }}
      - {{ . }}
      {{- end }}
      secretName: {{ .Values.ingress.tls.secretName }}
  {{- end }}
  rules:
    {{- $ctx := . }}
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /webui
            backend:
              serviceName: {{ template "master-external" $ctx }}
              servicePort: {{ $.Values.spark.master.webuiPort }}
          - path: /rest
            backend:
              serviceName: {{ template "master-external" $ctx }}
              servicePort: {{ $.Values.spark.master.restPort }}
    {{- end -}}
{{- end -}}
