apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "zeppelin.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ template "zeppelin.fullname" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        release: {{ .Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        app: {{ template "zeppelin.fullname" . }}
    spec:
      containers:
        - name: zeppelin
          image: {{ .Values.image.repository }}{{ .Values.image.name }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - zeppelin.sh
          {{- if .Values.spark.enabled }}
          env:
            - name: MASTER
              value: {{ template "zeppelin.spark-address" . }}
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          {{- if .Values.logCollector.enabled }}
          volumeMounts:
            - name: logdir
              mountPath: /zeppelin-0.7.1-bin-all/logs
          {{- end }}
        {{- if .Values.logCollector.enabled }}
        - name: filebeat
          image: "{{ .Values.logCollector.image.repository }}{{ .Values.logCollector.image.name }}:{{ .Values.logCollector.image.tag }}"
          imagePullPolicy: {{ .Values.logCollector.image.pullPolicy | quote }}
          volumeMounts:
            - name: filebeat-config
              mountPath: /etc/filebeat
            - name: logdir
              mountPath: /zeppelin-0.7.1-bin-all/logs
          command:
            - "filebeat"
            - "-c"
            - "/etc/filebeat/filebeat.yml"
            - "-e"
            - "-d"
            - "\"*\""
        {{- end }}
      {{- if .Values.logCollector.enabled }}
      volumes:
        - name: filebeat-config
          configMap:
            name: {{ printf "zeppelin-fb-%s" .Release.Name | trunc 55 | trimSuffix "-" }}
            items:
              - key: filebeat-yml
                path: filebeat.yml
        - name: logdir
          emptyDir: {}
      {{- end }}
