replicas: 3
antiAffinity: "soft" # or "hard" or "null"
probeInitialDelaySeconds: 15
probeTimeoutSeconds: 5

image:
  repository: mirantisworkloads/
  name: redis
  tag: "4.0"
  pullPolicy: IfNotPresent

resources:
  #requests:
  #  memory: 256Mi
  #  cpu: 100m

## Persist data to a persitent volume
persistence:
  type: emptyDir # or hostPath or PersistentVolumeClaim
  hostPath: ""
  ## storageClass: generic
  volumeSize: 5Gi

## Change redis configuration paramaters below.
config:
  redisPort: 6379
  sentinelPort: 26379
  slaveReadOnly: "no"

logCollector:
  enabled: false
  image:
    repository: mirantisworkloads/
    name: filebeat
    tag: 5.2.2
    pullPolicy: IfNotPresent
  # external logstash hosts
  logstashHost:
    - "" # host:port Ex: "logstash-logstash:5043"

prometheusExporter:
  enabled: false
  image:
    repository: oliver006/
    name: redis_exporter
    tag: v0.11.2
    pullPolicy: IfNotPresent
