kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "sentinel-fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ template "redis-fullname" . }}
data:
  sentinel.conf: |-
    sentinel monitor mymaster %master-ip% {{ .Values.config.redisPort }} 2
    sentinel down-after-milliseconds mymaster 60000
    sentinel failover-timeout mymaster 180000
    sentinel parallel-syncs mymaster 1
    bind 0.0.0.0
