# Default values for zookeeper.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

replicas: 3
antiAffinity: "soft" # or "hard"
probeInitialDelaySeconds: 15
probeTimeoutSeconds: 5
minAvailable: 2

serverPort: 2888
leaderElectionPort: 3888
clientPort: 2181

image:
  repository: mirantisworkloads/
  name: zookeeper
  tag: 3.5.3-beta
  pullPolicy: IfNotPresent

resources:
  #requests:
  #  cpu: 1
  #  memory: 2Gi
  #limits:
    #cpu: 4
    #memory: 10Gi

persistence:
  type: emptyDir # or hostPath or PersistentVolumeClaim

  #storageClass: ""
  volumeSize: 10Gi

  hostPath: ""

heapSize: 1G
logLevel: INFO

maxClientCnxns: 60

configFiles:
  # You can set zookeeper configs here.
  # Note, that the following configs will be overriden:
  # - dataDir=/var/lib/zookeeper/data
  # - dataLogDir=/var/lib/zookeeper/log
  # - standaloneEnabled=false
  # - dynamicConfigFile=/var/lib/zookeeper/conf/zoo.cfg.dynamic
  # - reconfigEnabled=true
  # - skipACL=yes
  # - 4lw.commands.whitelist=*
  zoo.cfg: |
    tickTime=2000
    initLimit=10
    syncLimit=5
    autopurge.purgeInterval=1
    autopurge.snapRetainCount=3
    maxClientCnxns=60

prometheusExporter:
  enabled: false

logCollector:
  enabled: false
  image:
    repository: mirantisworkloads/
    name: filebeat
    tag: 5.2.2
    pullPolicy: IfNotPresent
  # external logstash hosts
  logstashHost:
    - "" # host:port Ex: "logstash-logstash:5043"
